lang: pl
mysql:
  host: "localhost"
  port: 3306
  db: "SurvivalCG"
  user: "survival"
  usertable: "users"
  guildtable: "guilds"
  bantable: "bans"
  tableprefix: "scg_"
  password: ""
permissions:
  vip-permission: "lobby.svip"
stats:
  points: 10
protection:
  spawn-radius: 80
guild:
  team-pvp: false
  home-command: true
  max-clan-tag: 6  
  min-clan-tag: 3
  block-on-tnt: true
  block-tnt-time: 120
chat:
  guild-prefix: true
  prefix: '&7[&aHC&7]&7 '
blocked-guild-names:
  - "KUPA"
  - "ADMIN"
  - "DUPA"
#MAT:DUR:DATA:AMOUNT
required-items:
  - "DIAMOND:0:0:64"
  - "OBSIDIAN:0:0:32"
  - "ENDERPEARL:0:0:16"
  - "TNT:0:0:64"
  - "GOLDEN_APPLE:0:0:64"
  - "APPLE:0:0:64"
  - "CANE:0:0:64"
  - "BOOKSHELF:0:0:16"
cuboids:
  enabled: true
  radius: 50
  entry-protection: false
  damageCuboidItems:
    - DIAMOND_PICKAXE
  entry-notify: true
  entry-sound: true
  entry-sound-type: "WOLF_BARK"
teleport:
  cooldown: 10
hardcore:
  enabled: true
  bantime: "2h"
  kickmsg: "&7Bedziesz mogl wejsc na serwer &a{TIME}&7. Jako VIP mozesz wejsc bez czekania! Sklep: &ahttp://sklep.craftgames.pl/"
  lightnings: false
start-items:
  - STONE_PICKAXE:1
  - COOCKED_BEEF:64
  - ENDER_CHEST:1
blocked-worlds:
  - "world_nether"