name: SurvivalCG
version: 0.5
main: pl.grzegorz2047.survivalcg.SCG
description: Succesor of OpenGuild for CraftGames.pl
commands:
    ranking:
        description: Informacje nt. rankingu
        aliases: [rank, kille, zabojstwa, kd, points]
    guild:
        description: Pozwala tworzyc arene
        aliases: [team, gildia, watacha, g, druzyna]
    komendy:
        description: Podaje informacje o komendach
        aliases: [help, pomoc, commands]
    drop:
        description: Podaje informacje o dropie
    randomtp:
        description: Wysyla gracza w losowe miejsce na mapie
    admin:
        description: admin command
    vip:
        description: vip info